### ISSUE TITLE
Permission for Delprefix

### ISSUE THREAD

**Issue by elementalistic** [ModdedMinecraft/MMCPrefix#1]
On the sponge site you have it as *.del.* but the code expects *.delete.*

https://forums.spongepowered.org/t/mmcprefix-1-0-a-simple-custom-prefix-handler-api-5/16102

/Delprefix - mmcprefix.prefix.del.self - mmcprefix.prefix.del.others

**Comment by leelawd** [comment]
Oops, i do not know how i missed that. Thank you for bringing it to my attention, i have amended the documentation.
