### ISSUE TITLE
Luckperms compatability

### ISSUE THREAD

**Issue by elementalistic** [ModdedMinecraft/MMCPrefix#2]
So 2 issues currently regarding it.

First is the setprefix command correctly adds the prefix the first time and luckperms stores it as if it was added through it's own addprefix command.  The issue is, if you run the command a few times, with different prefixes you end up having them all added and only the one that is alphabetically first is used.  Luck perms allowing multiple prefixes with the same weighting(priority) on the same target(specific user in this case) is more likely a bug on it's end, as I can't see any reason to allow it.

Example:
/setprefix blah
/setprefix blahblah
/setprefix test

Luckperms then sets for the user:
prefix.100.blah
prefix.100.blahblah
prefix.100.test

==============

The other issue is delprefix, it says prefix deleted, but luckperms is not actually removing any prefix's from the user.  This is with both a single user prefix and multiple as per the above.

I'm using both commands below to verify the prefix is not being removed.
/lp user <user> permission info
/lp user <user> meta info

I'd almost say both are issues on luck perms side, but want to see what you say first.

**Comment by leelawd** [comment]
I don't think its specifically on LuckPerms side of things. I will have a look as soon as i can but I am just assuming that i would need to provide a different way to handle how each method is done. 

I did not really do extensive tests with LP since I had very little knowledge about it honestly.

**Comment by leelawd** [comment]
I spoke to the developer of LuckPerms after trying a few things. He is fixing this on his end. I will keep this issue open until I see an update for this.

**Comment by leelawd** [comment]
LuckPerms just fixed this, should be in the next version. https://github.com/lucko/LuckPerms/commit/bd97a7c5d257d75d7d0eaf2409f3672173dc4f54
