### ISSUE TITLE
Cant get plugin to work

### ISSUE THREAD

**Issue by DuckNuck** [ModdedMinecraft/MMCPrefix#5]
When i load up my sponge server it does not load this plugin

**Comment by leelawd** [comment]
Could you provide a FML-Server.log for me please?

**Comment by DuckNuck** [comment]
How do i do that?

**Comment by leelawd** [comment]
Easiest way is to upload the fml-server-latest.log in your log folder to a site like https://uploadfiles.io/

**Comment by DuckNuck** [comment]
https://ufile.io/ke71t

**Comment by leelawd** [comment]
I would need the one with fml in the title as it provides more in-depth information about startup and errors that occur, if thats not there you do not have forge installed

**Comment by DuckNuck** [comment]
https://ufile.io/levkv

**Comment by leelawd** [comment]
It appears that you have incorrectly installed SpongeForge

"Ignoring unknown file spongeforge-1.10.2-2281-5.2.0-BETA-2366 (2) - Shortcut.lnk in mods directory"

This is why the plugins will not load.

**Comment by DuckNuck** [comment]
so i have to reinstall spongeForge?

**Comment by leelawd** [comment]
Yes, you currently have it in an unknown format, Presumably a weblink shortcut.  So you will need to redownload the jar and install that

**Comment by DuckNuck** [comment]
May you send me the file?
1.10.2 please

**Comment by leelawd** [comment]
https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.10.2-2281-5.2.0-BETA-2371/spongeforge-1.10.2-2281-5.2.0-BETA-2371.jar

**Comment by DuckNuck** [comment]
thank you!

**Comment by leelawd** [comment]
no problem
